### ISSUE TITLE
Response includes irrelevant information

### ISSUE THREAD

**Issue by profnimrod** [bionic-gpt/bionic-gpt#177]
I'm trying to use Bionic-GPT to query my organization's corpus of resumes.  When I make a basic request such as "List the degrees that XXXX XXXXX has. Do not include degrees from other people in the list.", I get a list of degrees, but none of the ones included in the person of interests resume, but extracted from other resumes.  I'm guessing that when querying the vector database, chunks from multiple resumes are being returned, and the response built from those.  How do I ensure that when I want information about a specific individual, I ONLY get back information about this specific individual.

Given that resumes are fairly short (3-4 pages), would it make sense to increase the chunk size so that each chunk contains the whole resume?

**Comment by profnimrod** [comment]
Thanks for your timely response.  I'm using mistral 7B, which can handle a larger context. However, I think the problem is more fundamental, in that if I ask a question about a specific person's resume, chunks are being retrieved from the vector db that clearly have no association with the person I'm asking about. These are being added to the system content resulting in information coming back that mixes up the information from multiple resumes. 

I wonder if the methodology used just isn't compatible with this use case.  To work, when I ask about a particular person, chunks should only be returned from that person's resume only - presumably some meta data would need to be added to each chunk that includes the person's name and can be filtered on.

I'd also like to ask questions across the corpus of resumes, such as "List all the people with degrees and what degrees they have obtained" for example. Again, I don't think the current methodology is compatible with this kind of query.  Maybe I need to be looking at AutoGen, or something similar, so that each resume can be processed individually and then the output from each one aggregated into the final response.

Any ideas?

**Comment by ianpurton** [comment]
So I guess your requirements are something like

1. Load a whole bunch of CV's into the system
2. Be able to filter by the persons name and ask questions about their CV
3. Ask questions across all CV's

So I think your right about meta data and a solution would probably have to..

1. Process CV's and extra meta data i.e. persons name, email. Probably their already exists a solution for this.
2. In the UI filter based on name, email etc.
3. Fill the context with 1 CV (based on above filter) and allow the user to ask questions.
4. Run a natural language question across CV's and aggregate results.


## Querying individual CV's

So I could image a future version of Bionic GPT with something like the following for processing incoming data.

1. Specify a prompt so that the LLM extracts meta data on document upload for each document. Meta data then gets stored with chunks.
2. In the console, allow the user to filter based on meta data and add that to the query when retrieving chunks. Perhaps with can do that with natural language
3. Fill the context form that document until full and allow the user to query it.

## For aggregation

> List all the people with degrees and what degrees they have obtained

Perhaps something like you specify a prompt that runs on every document to produce a summary and then a further prompt that aggregates results.

## Requirements for Bionic

- Allow user to specify a prompt that extracts meta data from incoming documents.
- Filter based on meta data when querying the DB. Natural language or do we need UI
- Allow user to run prompts against datasets and summarize the contents.
- Allow user to specify a prompt that aggregates summaries.

I would have to think about this some more, perhaps theirs an easier solution.

Can you let me know if my reasoning sounds about right?
