### ISSUE TITLE
Can we use openai-node?

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#209]
https://github.com/openai/openai-node

- [ ] Try from front end
- [ ] How much will backend need to change
- [ ] Doe sit handle the markdown?

**Comment by Tostino** [comment]
Just wondering, if the problem is the lack of a rust client, why not use [swagger codegen](https://github.com/swagger-api/swagger-codegen) to build a rust api client from OpenAI's [OpenAPI spec](https://github.com/openai/openai-openapi/blob/master/openapi.yaml)?

Moving some of that logic to the front end *could* work, but it would limit what you are able to do on the backend later without the web client's involvement.

**Comment by ianpurton** [comment]
@Tostino There is a rust client for Open AI. That's not the issue.

The issue is we're maintaing to web components on the front end. https://github.com/bionic-gpt/bionic-gpt/tree/main/crates/asset-pipeline/web-components

Namely `response-formatter` and `streaming-chat`

So my theory is every web based client has the same issue. Streaming the chat and handling errors (for example if a user has used up all their tokens on open AI)

Turning streaming results from the LLM into something to display on the web page. i.e. handling markdown and code etc.

**Comment by ianpurton** [comment]
Closing, as decision is to continue maintaining our own.
