### ISSUE TITLE
"Error occurred while generating."

### ISSUE THREAD

**Issue by bigbeef105** [bionic-gpt/bionic-gpt#260]
I installed and ran as instructed without any issues.  Using an M2 Macbook with 96GB of ram.

Simply typed a test prompt: "hi"

2023-12-29 20:25:03 app-1             | 2023-12-30T01:25:03.489638Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"
2023-12-29 20:25:03 app-1             | 2023-12-30T01:25:03.493357Z  INFO axum_server::prompt: Retrieved 10 chunks
2023-12-29 20:25:03 app-1             | 2023-12-30T01:25:03.493424Z  INFO axum_server::prompt: Retrieved 10 chunks
2023-12-29 20:25:03 app-1             | 2023-12-30T01:25:03.493726Z  INFO axum_server::prompt: Retrieved 0 history items
2023-12-29 20:25:03 app-1             | 2023-12-30T01:25:03.493733Z  INFO axum_server::prompt: Using context size of 819
2023-12-29 20:25:04 app-1             | 2023-12-30T01:25:04.276497Z  INFO axum_server::prompt: Retrieved 0 history items
2023-12-29 20:25:04 app-1             | 2023-12-30T01:25:04.276521Z  INFO axum_server::prompt: Using context size of 819
2023-12-29 20:25:05 app-1             | 2023-12-30T01:25:05.106391Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"
2023-12-29 20:25:05 app-1             | 2023-12-30T01:25:05.108398Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"

**Comment by tbendien** [comment]
@bigbeef105 
It could be that the inference engine (TGI) included in the default Bionic install and/or the AWQ model which is preconfigured in the Bionic docker-compose.yml don't work properly with the M2 silicon (just a guess, I don't have an M2 machine to test on). There could also be other issues which are stopping your Bionic install from working, but try the items below to see if you can get things working:

Can you try installing Ollama on your M2 Mac  and seeing if that works by itself? 
```
https://ollama.ai/download
```

Ollama models are here: 
```
https://ollama.ai/library
```
For example, you might like to start with a small model first like: 
```
https://ollama.ai/library/llama2:7b
```
To download and run that model after you have installed Ollama, simply open a terminal session and type in: 
```
ollama run llama2:7b
```
The model should start and you will see a prompt: >>>

Then you can simply start typing in questions and hit enter to see the response.

Once you can see that Ollama runs on your M2 Mac, shut it down by entering:

```
ctrl D
```
or
```
/bye 
```
to stop Ollama.

If your machine runs models using Ollama (you have to use models from the Ollama website, models from other places like Hugging Face probably won't work on Ollama) then thats a step in the right direction.

Then to run Bionic you have to get the Bionic Ollama yaml file:

```
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose-ollama.yml
```
Modify the yaml file to include the Ollama model you want to run. 

An example is given below of what the line in the yaml with the Ollama model should look like after the modification, in this case for the Llama2 7B base model:
```
    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/llama2:7b --api_base http://ollama:11434 --host 0.0.0.0 --port 3000"]
```
After you have modified the yaml, saved it with the Ollama model ID you want, start Bionic running and wait until it is fully finished and up. You have to issue the docker-compose command while you are in the directory where the yaml file is located.

Note that the docker-compose-ollama.yml file has not been renamed to indicate which model it is going to connect to via Ollama. 

For convenience, I rename the docker-compose-ollama.yml files with the model name so I can tell them apart.
(for example: docker-compose-ollama-llama2:7b.yml)

Start Bionic:

```
docker-compose -f docker-compose.yml -f docker-compose-ollama.yml up
```

Wait until everyhing is finished and ready.

Assuming you did not change the docker-compose-ollama.yml file name, run this command to start Ollama and have it connect to Bionic:

Open another terminal session on your host, and type in:
```
docker exec -it bionic_ollama_1 ollama run llama2:7b
```
Change the model ID as you wish, based on the model you want to run.
Keep in mind that the model entered in the docker-compose-ollama.yml file must match the docker exec command.

What I usually do is create multiple docker-compose-ollama files, each with their own model name added to the end of the filename. I also save the docker exec commands on my runbook notes document (Google doc) so that I can quickly switch between models.

Once the Bionic containers and the Ollama containers are running, you should be able to go to the gui on your browser and run the Bionic UI:
```
http://localhost:7800
```
let me know if that helps, and if you get Bionic working?

**Comment by kulbinderdio** [comment]
@bigbeef105 I'm assuming you were trying ollama setup. If so, there was a change to that config file that turned out to be specific for Nvidia. This has now been reverted and is back inline with the documentation.
If this doesn't resolve your issue can you provide details on the configuration you are trying to start

**Comment by bigbeef105** [comment]
@tbendien Thank you for your [reply](https://github.com/bionic-gpt/bionic-gpt/issues/260#issuecomment-1872431128).  I have proceeded to this step: "docker exec -it bionic_ollama_1 ollama run llama2:7b"

I'm stuck here, something very stupid I'm sure.

My terminal returns: "Error response from daemon: No such container: bionic_ollama_1"

I viewed the docker container which was turned on in the previous step within docker desktop, and see this:

<img width="1076" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/182c9071-8026-4f63-b17b-c8d6c0e2b8b3">

**Comment by kulbinderdio** [comment]
Hi Matt

Did you follow the instructions on https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/
In particular setting up ollama link (when you go through the links you actually need to end up here https://hub.docker.com/r/ollama/ollama)

The way this currently works for Apple Silicon is that you need to start ollama up seperately
```
docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```
and then  exec into it. 
```
docker exec -it ollama ollama run llama2
```
This will load the llama2 model into ollama

before starting up the remaining containers ensure that the docker-compose-ollama.yml has the same model name as the one in the exec command above

hope that helps

**Comment by bigbeef105** [comment]
Thank you.  I somehow missed this step.

**Comment by bigbeef105** [comment]
Thank you - I will try it out - is the correct approach just to pull down the updated docker compose.yml?
