### ISSUE TITLE
Database Backup Strategy

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#566]

**Comment by tbendien** [comment]
We tried doing this via PG Admin, but got an error message that the Backup command does not have permissions to lock the database for the backup. This is likely because the login for the Postgres for PG Admin is read only. Is there a way to configure a write enabled role that we can use to log into PG Admin or other DB management tools?

**Comment by kulbinderdio** [comment]
Try the following

Log into the cluster (k9s) and create a session on the DB pod

type 
   psql
followed by 
   CREATE ROLE mysuperuser2 WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'mysuperpass2';

further details on creating roles can be found here
https://docs.rackspace.com/docs/postgresql-creating-and-dropping-roles#:~:text=To%20create%20a%20superuser%2C%20run,specifies%20a%20non%2Dempty%20password.&text=remote%20connections%20to%20the%20database.

**Comment by tbendien** [comment]
That worked, thank you Dio!!

**Comment by kulbinderdio** [comment]
completed
